//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLCPrinter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BLCEntities1 : DbContext
    {
        public BLCEntities1()
            : base("name=BLCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTRACTE> CONTRACTE { get; set; }
        public virtual DbSet<LIBRARIE> LIBRARIE { get; set; }
        public virtual DbSet<PERSOANE> PERSOANE { get; set; }
        public virtual DbSet<SERVICII_CONTRACT> SERVICII_CONTRACT { get; set; }
        public virtual DbSet<Utilizatori> Utilizatori { get; set; }
        public virtual DbSet<Incasari> Incasari { get; set; }
    }
}
