//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLCPrinter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BLCEntities : DbContext
    {
        public BLCEntities()
            : base("name=BLCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CONTRACTE> CONTRACTEs { get; set; }
        public DbSet<LIBRARIE> LIBRARIEs { get; set; }
        public DbSet<PERSOANE> PERSOANEs { get; set; }
        public DbSet<SERVICII_CONTRACT> SERVICII_CONTRACT { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Incasari> Incasaris { get; set; }
    }
}
