//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLCPrinter
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LIBRARIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRARIE()
        {
            this.CONTRACTE = new HashSet<CONTRACTE>();
            this.PERSOANE = new HashSet<PERSOANE>();
            this.SERVICII_CONTRACT = new HashSet<SERVICII_CONTRACT>();
        }

        [Display(Name = "ID")]
        public int L_ID { get; set; }
        [Display(Name = "Nume")]
        public string L_NUME { get; set; }
        [Display(Name = "Tip")]
        public string L_TIP { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACTE> CONTRACTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSOANE> PERSOANE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICII_CONTRACT> SERVICII_CONTRACT { get; set; }
    }
}
