//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLCPrinter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSOANE_EXTRA
    {
        public int PE_ID { get; set; }
        public int PE_CONTRACT_ID { get; set; }
        public string PE_NUME { get; set; }
        public Nullable<System.DateTime> PE_DATA_NASTERII { get; set; }
        public string PE_COPIL { get; set; }
    
        public virtual CONTRACTE CONTRACTE { get; set; }
    }
}
